name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/workflows/maven.yml'
  pull_request:
    branches: [ "main" ]

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: See info
        run: echo "${{ toJson(github.event.pusher.name) }}"
  build:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Cache deps and target
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          **/target
        key: ${{ runner.os }}-maven-deps-${{ hashFiles('**/pom.xml') }}
    - name: Compile
      run: mvn clean compile
  test-smoke:
    if: ${{ false }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Cache deps and target
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            **/target
          key: ${{ runner.os }}-maven-deps-${{ hashFiles('**/pom.xml') }}
      - name: Run smoke test
        run: mvn test
  test-all:
    needs:
      [build, test-smoke]
    strategy:
      matrix:
        version: [17, 18]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: 'temurin'
          cache: maven
      - name: Cache deps and target
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            **/target
          key: ${{ runner.os }}-maven-deps-${{ hashFiles('**/pom.xml') }}
      - name: Run smoke test
        run: mvn test